config/routes.rb
Rails.application.routes.draw do

  resources :datasets do
    resources :people
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "datasets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dataset.rb
class Dataset < ApplicationRecord
  has_many :people
  
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :dataset
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/datasets_controller.rb
class DatasetsController < ApplicationController
  before_action :set_dataset, only: [:show, :edit, :update, :destroy]

  # GET /datasets
  # GET /datasets.json
  def index
    @datasets = Dataset.all
  end

  # GET /datasets/1
  # GET /datasets/1.json
  def show
  end

  # GET /datasets/new
  def new
    @dataset = Dataset.new
  end

  # GET /datasets/1/edit
  def edit
  end

  # POST /datasets
  # POST /datasets.json
  def create
    @dataset = Dataset.new(dataset_params)

    respond_to do |format|
      if @dataset.save
        format.html { redirect_to @dataset, notice: 'Dataset was successfully created.' }
        format.json { render :show, status: :created, location: @dataset }
      else
        format.html { render :new }
        format.json { render json: @dataset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /datasets/1
  # PATCH/PUT /datasets/1.json
  def update
    respond_to do |format|
      if @dataset.update(dataset_params)
        format.html { redirect_to @dataset, notice: 'Dataset was successfully updated.' }
        format.json { render :show, status: :ok, location: @dataset }
      else
        format.html { render :edit }
        format.json { render json: @dataset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datasets/1
  # DELETE /datasets/1.json
  def destroy
    @dataset.destroy
    respond_to do |format|
      format.html { redirect_to datasets_url, notice: 'Dataset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dataset
      @dataset = Dataset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dataset_params
      params.require(:dataset).permit(:dataset_name, :dataset_owner, :dataset_owner_contact, :dataset_url, :dataset_date_imported, :dataset_update_continously, :dataset_last_update)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_dataset
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = @dataset.people.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @dataset, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_dataset
      @dataset = Dataset.find(params[:dataset_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = @dataset.people.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :second_name, :first_apellido, :second_apellido, :birth_date, :birth_country, :birth_state, :nationality, :alias, :sex, :gender, :sexual_orientation, :sexchange_surgery, :sexchange_surgery_type, :amputation, :amputation_type, :chronic_disease, :chronic_disease_type, :prothesis, :prothesis_type, :glasses, :contact_lens, :diopters, :weight, :height, :skin_type, :eye_color, :hair_type, :hair_color, :facial_hair, :body_hair, :tattoos, :tattoos_type, :piercings, :piercings_type, :facial_moles, :facial_moles_type, :facial_birth_marks, :facial_birth_marks_type, :facial_scars, :facial_scars_type, :hands_moles, :hands_moles_type, :hands_birth_marks, :hands_birth_marks_type, :hands_scars, :hands_scars_type, :physical_disabilities, :physical_disabilities_type, :mental_disabilities, :mental_disabilities_string_type, :mental_illness, :mental_illness_type, :sight_disabilites, :sight_disabilities_type, :ear_disabilities, :ear_disabilities_type, :ethnicity, :id_document, :id_type, :id_photo, :biography_municipality, :biography_city, :biography_state, :biography_country, :activist, :journalist, :migrant, :occupation, :position, :event_date, :event_time, :event_street, :event_street_number, :event_neighborhood, :event_municipality, :event_city, :event_postal, :event_state, :event_country, :ls_date, :ls_time, :ls_street, :ls_street_number, :ls_neighborhood, :ls_municipality, :ls_city, :ls_postal, :ls_state, :ls_country, :ls_clothes, :ls_clothes_top, :ls_clothes_top_color, :ls_clothes_bottom, :ls_clothes_bottom_color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datasets_helper.rb
module DatasetsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/datasets/_form.html.erb
<%= form_with(model: dataset, local: true) do |form| %>
  <% if dataset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dataset.errors.count, "error") %> prohibited this dataset from being saved:</h2>

      <ul>
      <% dataset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dataset_name %>
    <%= form.text_field :dataset_name, id: :dataset_dataset_name %>
  </div>

  <div class="field">
    <%= form.label :dataset_owner %>
    <%= form.text_field :dataset_owner, id: :dataset_dataset_owner %>
  </div>

  <div class="field">
    <%= form.label :dataset_owner_contact %>
    <%= form.text_field :dataset_owner_contact, id: :dataset_dataset_owner_contact %>
  </div>

  <div class="field">
    <%= form.label :dataset_url %>
    <%= form.text_field :dataset_url, id: :dataset_dataset_url %>
  </div>

  <div class="field">
    <%= form.label :dataset_date_imported %>
    <%= form.datetime_select :dataset_date_imported, id: :dataset_dataset_date_imported %>
  </div>

  <div class="field">
    <%= form.label :dataset_update_continously %>
    <%= form.check_box :dataset_update_continously, id: :dataset_dataset_update_continously %>
  </div>

  <div class="field">
    <%= form.label :dataset_last_update %>
    <%= form.datetime_select :dataset_last_update, id: :dataset_dataset_last_update %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/datasets/edit.html.erb
<h1>Editing Dataset</h1>

<%= render 'form', dataset: @dataset %>

<%= link_to 'Show', @dataset %> |
<%= link_to 'Back', datasets_path %>

app/views/datasets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Datasets</h1>

<table>
  <thead>
    <tr>
      <th>Dataset name</th>
      <th>Dataset owner</th>
      <th>Dataset owner contact</th>
      <th>Dataset url</th>
      <th>Dataset date imported</th>
      <th>Dataset update continously</th>
      <th>Dataset last update</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @datasets.each do |dataset| %>
      <tr>
        <td><%= dataset.dataset_name %></td>
        <td><%= dataset.dataset_owner %></td>
        <td><%= dataset.dataset_owner_contact %></td>
        <td><%= dataset.dataset_url %></td>
        <td><%= dataset.dataset_date_imported %></td>
        <td><%= dataset.dataset_update_continously %></td>
        <td><%= dataset.dataset_last_update %></td>
        <td><%= link_to 'Show', dataset %></td>
        <td><%= link_to 'Edit', edit_dataset_path(dataset) %></td>
        <td><%= link_to 'Destroy', dataset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dataset', new_dataset_path %>

app/views/datasets/new.html.erb
<h1>New Dataset</h1>

<%= render 'form', dataset: @dataset %>

<%= link_to 'Back', datasets_path %>

app/views/datasets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dataset name:</strong>
  <%= @dataset.dataset_name %>
</p>

<p>
  <strong>Dataset owner:</strong>
  <%= @dataset.dataset_owner %>
</p>

<p>
  <strong>Dataset owner contact:</strong>
  <%= @dataset.dataset_owner_contact %>
</p>

<p>
  <strong>Dataset url:</strong>
  <%= @dataset.dataset_url %>
</p>

<p>
  <strong>Dataset date imported:</strong>
  <%= @dataset.dataset_date_imported %>
</p>

<p>
  <strong>Dataset update continously:</strong>
  <%= @dataset.dataset_update_continously %>
</p>

<p>
  <strong>Dataset last update:</strong>
  <%= @dataset.dataset_last_update %>
</p>

<%= render @dataset.people %>

<%= link_to 'Registra una nueva persona', new_dataset_person_path(@dataset)  %>

<%= link_to 'Edit', edit_dataset_path(@dataset) %> |
<%= link_to 'Back', datasets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buscandonos19s</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_person.html.erb
<p><%= person.first_name %> <%= person.second_name %> <%= person.first_apellido %> <%= person.second_apellido %>  <%= link_to 'Edit', edit_dataset_person_path(@dataset, person) %> <%= link_to 'Destroy', dataset_person_path(@dataset, person), method: :delete, data: { confirm: 'Are you sure?' } %></p>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', dataset_person_path %> |
<%= link_to 'Back', dataset_path(@dataset) %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Second name</th>
      <th>First apellido</th>
      <th>Second apellido</th>
      <th>Birth date</th>
      <th>Birth country</th>
      <th>Birth state</th>
      <th>Nationality</th>
      <th>Alias</th>
      <th>Sex</th>
      <th>Gender</th>
      <th>Sexual orientation</th>
      <th>Sexchange surgery</th>
      <th>Sexchange surgery type</th>
      <th>Amputation</th>
      <th>Amputation type</th>
      <th>Chronic disease</th>
      <th>Chronic disease type</th>
      <th>Prothesis</th>
      <th>Prothesis type</th>
      <th>Glasses</th>
      <th>Contact lens</th>
      <th>Diopters</th>
      <th>Weight</th>
      <th>Height</th>
      <th>Skin type</th>
      <th>Eye color</th>
      <th>Hair type</th>
      <th>Hair color</th>
      <th>Facial hair</th>
      <th>Body hair</th>
      <th>Tattoos</th>
      <th>Tattoos type</th>
      <th>Piercings</th>
      <th>Piercings type</th>
      <th>Facial moles</th>
      <th>Facial moles type</th>
      <th>Facial birth marks</th>
      <th>Facial birth marks type</th>
      <th>Facial scars</th>
      <th>Facial scars type</th>
      <th>Hands moles</th>
      <th>Hands moles type</th>
      <th>Hands birth marks</th>
      <th>Hands birth marks type</th>
      <th>Hands scars</th>
      <th>Hands scars type</th>
      <th>Physical disabilities</th>
      <th>Physical disabilities type</th>
      <th>Mental disabilities</th>
      <th>Mental disabilities string type</th>
      <th>Mental illness</th>
      <th>Mental illness type</th>
      <th>Sight disabilites</th>
      <th>Sight disabilities type</th>
      <th>Ear disabilities</th>
      <th>Ear disabilities type</th>
      <th>Ethnicity</th>
      <th>Id document</th>
      <th>Id type</th>
      <th>Id photo</th>
      <th>Biography municipality</th>
      <th>Biography city</th>
      <th>Biography state</th>
      <th>Biography country</th>
      <th>Activist</th>
      <th>Journalist</th>
      <th>Migrant</th>
      <th>Occupation</th>
      <th>Position</th>
      <th>Event date</th>
      <th>Event time</th>
      <th>Event street</th>
      <th>Event street number</th>
      <th>Event neighborhood</th>
      <th>Event municipality</th>
      <th>Event city</th>
      <th>Event postal</th>
      <th>Event state</th>
      <th>Event country</th>
      <th>Ls date</th>
      <th>Ls time</th>
      <th>Ls street</th>
      <th>Ls street number</th>
      <th>Ls neighborhood</th>
      <th>Ls municipality</th>
      <th>Ls city</th>
      <th>Ls postal</th>
      <th>Ls state</th>
      <th>Ls country</th>
      <th>Ls clothes</th>
      <th>Ls clothes top</th>
      <th>Ls clothes top color</th>
      <th>Ls clothes bottom</th>
      <th>Ls clothes bottom color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.second_name %></td>
        <td><%= person.first_apellido %></td>
        <td><%= person.second_apellido %></td>
        <td><%= person.birth_date %></td>
        <td><%= person.birth_country %></td>
        <td><%= person.birth_state %></td>
        <td><%= person.nationality %></td>
        <td><%= person.alias %></td>
        <td><%= person.sex %></td>
        <td><%= person.gender %></td>
        <td><%= person.sexual_orientation %></td>
        <td><%= person.sexchange_surgery %></td>
        <td><%= person.sexchange_surgery_type %></td>
        <td><%= person.amputation %></td>
        <td><%= person.amputation_type %></td>
        <td><%= person.chronic_disease %></td>
        <td><%= person.chronic_disease_type %></td>
        <td><%= person.prothesis %></td>
        <td><%= person.prothesis_type %></td>
        <td><%= person.glasses %></td>
        <td><%= person.contact_lens %></td>
        <td><%= person.diopters %></td>
        <td><%= person.weight %></td>
        <td><%= person.height %></td>
        <td><%= person.skin_type %></td>
        <td><%= person.eye_color %></td>
        <td><%= person.hair_type %></td>
        <td><%= person.hair_color %></td>
        <td><%= person.facial_hair %></td>
        <td><%= person.body_hair %></td>
        <td><%= person.tattoos %></td>
        <td><%= person.tattoos_type %></td>
        <td><%= person.piercings %></td>
        <td><%= person.piercings_type %></td>
        <td><%= person.facial_moles %></td>
        <td><%= person.facial_moles_type %></td>
        <td><%= person.facial_birth_marks %></td>
        <td><%= person.facial_birth_marks_type %></td>
        <td><%= person.facial_scars %></td>
        <td><%= person.facial_scars_type %></td>
        <td><%= person.hands_moles %></td>
        <td><%= person.hands_moles_type %></td>
        <td><%= person.hands_birth_marks %></td>
        <td><%= person.hands_birth_marks_type %></td>
        <td><%= person.hands_scars %></td>
        <td><%= person.hands_scars_type %></td>
        <td><%= person.physical_disabilities %></td>
        <td><%= person.physical_disabilities_type %></td>
        <td><%= person.mental_disabilities %></td>
        <td><%= person.mental_disabilities_string_type %></td>
        <td><%= person.mental_illness %></td>
        <td><%= person.mental_illness_type %></td>
        <td><%= person.sight_disabilites %></td>
        <td><%= person.sight_disabilities_type %></td>
        <td><%= person.ear_disabilities %></td>
        <td><%= person.ear_disabilities_type %></td>
        <td><%= person.ethnicity %></td>
        <td><%= person.id_document %></td>
        <td><%= person.id_type %></td>
        <td><%= person.id_photo %></td>
        <td><%= person.biography_municipality %></td>
        <td><%= person.biography_city %></td>
        <td><%= person.biography_state %></td>
        <td><%= person.biography_country %></td>
        <td><%= person.activist %></td>
        <td><%= person.journalist %></td>
        <td><%= person.migrant %></td>
        <td><%= person.occupation %></td>
        <td><%= person.position %></td>
        <td><%= person.event_date %></td>
        <td><%= person.event_time %></td>
        <td><%= person.event_street %></td>
        <td><%= person.event_street_number %></td>
        <td><%= person.event_neighborhood %></td>
        <td><%= person.event_municipality %></td>
        <td><%= person.event_city %></td>
        <td><%= person.event_postal %></td>
        <td><%= person.event_state %></td>
        <td><%= person.event_country %></td>
        <td><%= person.ls_date %></td>
        <td><%= person.ls_time %></td>
        <td><%= person.ls_street %></td>
        <td><%= person.ls_street_number %></td>
        <td><%= person.ls_neighborhood %></td>
        <td><%= person.ls_municipality %></td>
        <td><%= person.ls_city %></td>
        <td><%= person.ls_postal %></td>
        <td><%= person.ls_state %></td>
        <td><%= person.ls_country %></td>
        <td><%= person.ls_clothes %></td>
        <td><%= person.ls_clothes_top %></td>
        <td><%= person.ls_clothes_top_color %></td>
        <td><%= person.ls_clothes_bottom %></td>
        <td><%= person.ls_clothes_bottom_color %></td>
        <td><%= link_to 'Show', dataset_person_path(@dataset.person) %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', dataset_path(@dataset) %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Second name:</strong>
  <%= @person.second_name %>
</p>

<p>
  <strong>First apellido:</strong>
  <%= @person.first_apellido %>
</p>

<p>
  <strong>Second apellido:</strong>
  <%= @person.second_apellido %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @person.birth_date %>
</p>

<p>
  <strong>Birth country:</strong>
  <%= @person.birth_country %>
</p>

<p>
  <strong>Birth state:</strong>
  <%= @person.birth_state %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @person.nationality %>
</p>

<p>
  <strong>Alias:</strong>
  <%= @person.alias %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @person.sex %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @person.gender %>
</p>

<p>
  <strong>Sexual orientation:</strong>
  <%= @person.sexual_orientation %>
</p>

<p>
  <strong>Sexchange surgery:</strong>
  <%= @person.sexchange_surgery %>
</p>

<p>
  <strong>Sexchange surgery type:</strong>
  <%= @person.sexchange_surgery_type %>
</p>

<p>
  <strong>Amputation:</strong>
  <%= @person.amputation %>
</p>

<p>
  <strong>Amputation type:</strong>
  <%= @person.amputation_type %>
</p>

<p>
  <strong>Chronic disease:</strong>
  <%= @person.chronic_disease %>
</p>

<p>
  <strong>Chronic disease type:</strong>
  <%= @person.chronic_disease_type %>
</p>

<p>
  <strong>Prothesis:</strong>
  <%= @person.prothesis %>
</p>

<p>
  <strong>Prothesis type:</strong>
  <%= @person.prothesis_type %>
</p>

<p>
  <strong>Glasses:</strong>
  <%= @person.glasses %>
</p>

<p>
  <strong>Contact lens:</strong>
  <%= @person.contact_lens %>
</p>

<p>
  <strong>Diopters:</strong>
  <%= @person.diopters %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @person.weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @person.height %>
</p>

<p>
  <strong>Skin type:</strong>
  <%= @person.skin_type %>
</p>

<p>
  <strong>Eye color:</strong>
  <%= @person.eye_color %>
</p>

<p>
  <strong>Hair type:</strong>
  <%= @person.hair_type %>
</p>

<p>
  <strong>Hair color:</strong>
  <%= @person.hair_color %>
</p>

<p>
  <strong>Facial hair:</strong>
  <%= @person.facial_hair %>
</p>

<p>
  <strong>Body hair:</strong>
  <%= @person.body_hair %>
</p>

<p>
  <strong>Tattoos:</strong>
  <%= @person.tattoos %>
</p>

<p>
  <strong>Tattoos type:</strong>
  <%= @person.tattoos_type %>
</p>

<p>
  <strong>Piercings:</strong>
  <%= @person.piercings %>
</p>

<p>
  <strong>Piercings type:</strong>
  <%= @person.piercings_type %>
</p>

<p>
  <strong>Facial moles:</strong>
  <%= @person.facial_moles %>
</p>

<p>
  <strong>Facial moles type:</strong>
  <%= @person.facial_moles_type %>
</p>

<p>
  <strong>Facial birth marks:</strong>
  <%= @person.facial_birth_marks %>
</p>

<p>
  <strong>Facial birth marks type:</strong>
  <%= @person.facial_birth_marks_type %>
</p>

<p>
  <strong>Facial scars:</strong>
  <%= @person.facial_scars %>
</p>

<p>
  <strong>Facial scars type:</strong>
  <%= @person.facial_scars_type %>
</p>

<p>
  <strong>Hands moles:</strong>
  <%= @person.hands_moles %>
</p>

<p>
  <strong>Hands moles type:</strong>
  <%= @person.hands_moles_type %>
</p>

<p>
  <strong>Hands birth marks:</strong>
  <%= @person.hands_birth_marks %>
</p>

<p>
  <strong>Hands birth marks type:</strong>
  <%= @person.hands_birth_marks_type %>
</p>

<p>
  <strong>Hands scars:</strong>
  <%= @person.hands_scars %>
</p>

<p>
  <strong>Hands scars type:</strong>
  <%= @person.hands_scars_type %>
</p>

<p>
  <strong>Physical disabilities:</strong>
  <%= @person.physical_disabilities %>
</p>

<p>
  <strong>Physical disabilities type:</strong>
  <%= @person.physical_disabilities_type %>
</p>

<p>
  <strong>Mental disabilities:</strong>
  <%= @person.mental_disabilities %>
</p>

<p>
  <strong>Mental disabilities string type:</strong>
  <%= @person.mental_disabilities_string_type %>
</p>

<p>
  <strong>Mental illness:</strong>
  <%= @person.mental_illness %>
</p>

<p>
  <strong>Mental illness type:</strong>
  <%= @person.mental_illness_type %>
</p>

<p>
  <strong>Sight disabilites:</strong>
  <%= @person.sight_disabilites %>
</p>

<p>
  <strong>Sight disabilities type:</strong>
  <%= @person.sight_disabilities_type %>
</p>

<p>
  <strong>Ear disabilities:</strong>
  <%= @person.ear_disabilities %>
</p>

<p>
  <strong>Ear disabilities type:</strong>
  <%= @person.ear_disabilities_type %>
</p>

<p>
  <strong>Ethnicity:</strong>
  <%= @person.ethnicity %>
</p>

<p>
  <strong>Id document:</strong>
  <%= @person.id_document %>
</p>

<p>
  <strong>Id type:</strong>
  <%= @person.id_type %>
</p>

<p>
  <strong>Id photo:</strong>
  <%= @person.id_photo %>
</p>

<p>
  <strong>Biography municipality:</strong>
  <%= @person.biography_municipality %>
</p>

<p>
  <strong>Biography city:</strong>
  <%= @person.biography_city %>
</p>

<p>
  <strong>Biography state:</strong>
  <%= @person.biography_state %>
</p>

<p>
  <strong>Biography country:</strong>
  <%= @person.biography_country %>
</p>

<p>
  <strong>Activist:</strong>
  <%= @person.activist %>
</p>

<p>
  <strong>Journalist:</strong>
  <%= @person.journalist %>
</p>

<p>
  <strong>Migrant:</strong>
  <%= @person.migrant %>
</p>

<p>
  <strong>Occupation:</strong>
  <%= @person.occupation %>
</p>

<p>
  <strong>Position:</strong>
  <%= @person.position %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @person.event_date %>
</p>

<p>
  <strong>Event time:</strong>
  <%= @person.event_time %>
</p>

<p>
  <strong>Event street:</strong>
  <%= @person.event_street %>
</p>

<p>
  <strong>Event street number:</strong>
  <%= @person.event_street_number %>
</p>

<p>
  <strong>Event neighborhood:</strong>
  <%= @person.event_neighborhood %>
</p>

<p>
  <strong>Event municipality:</strong>
  <%= @person.event_municipality %>
</p>

<p>
  <strong>Event city:</strong>
  <%= @person.event_city %>
</p>

<p>
  <strong>Event postal:</strong>
  <%= @person.event_postal %>
</p>

<p>
  <strong>Event state:</strong>
  <%= @person.event_state %>
</p>

<p>
  <strong>Event country:</strong>
  <%= @person.event_country %>
</p>

<p>
  <strong>Ls date:</strong>
  <%= @person.ls_date %>
</p>

<p>
  <strong>Ls time:</strong>
  <%= @person.ls_time %>
</p>

<p>
  <strong>Ls street:</strong>
  <%= @person.ls_street %>
</p>

<p>
  <strong>Ls street number:</strong>
  <%= @person.ls_street_number %>
</p>

<p>
  <strong>Ls neighborhood:</strong>
  <%= @person.ls_neighborhood %>
</p>

<p>
  <strong>Ls municipality:</strong>
  <%= @person.ls_municipality %>
</p>

<p>
  <strong>Ls city:</strong>
  <%= @person.ls_city %>
</p>

<p>
  <strong>Ls postal:</strong>
  <%= @person.ls_postal %>
</p>

<p>
  <strong>Ls state:</strong>
  <%= @person.ls_state %>
</p>

<p>
  <strong>Ls country:</strong>
  <%= @person.ls_country %>
</p>

<p>
  <strong>Ls clothes:</strong>
  <%= @person.ls_clothes %>
</p>

<p>
  <strong>Ls clothes top:</strong>
  <%= @person.ls_clothes_top %>
</p>

<p>
  <strong>Ls clothes top color:</strong>
  <%= @person.ls_clothes_top_color %>
</p>

<p>
  <strong>Ls clothes bottom:</strong>
  <%= @person.ls_clothes_bottom %>
</p>

<p>
  <strong>Ls clothes bottom color:</strong>
  <%= @person.ls_clothes_bottom_color %>
</p>

<%= link_to 'Edit', edit_dataset_person_path(@dataset, @person) %> |
<%= link_to 'Back', dataset_person_path(@dataset, @person) %>